# Write a function that returns the smallest non-negative number 
# which can be generated by using all the digits with odd values 
# of a given number.

# Sample:

# Input: n = 31020457

# Odd digits are: 3,1,5,7

# Output: 1357
n = 31020457
def odd_num(digit):

    if not digit: return 0

    s = sorted(str(abs(digit)))
    odd = []
    for num in s:
        if int(num) % 2 != 0:
            odd.append(num)
    if not odd: return 0
    return int("".join(odd))
print(odd_num(n))

    

