








#question 4
workshops = [(2020, 3), (2020, 2), (2021, 4), (2023, 10), (2024, 1)]


def max_classes(workshops):
    
    years_total = dict()
    for y,c in workshops:
        years_total[y] = years_total.get(y,0) + c
    
    sorted_years = sorted(years_total.keys())
    
    max_classes = years_total[sorted_years[0]]
    run_sum = years_total[sorted_years[0]]
    
    for i in range(1,len(sorted_years)):
        if sorted_years[i] != sorted_years[i-1] + 1:
            run_sum = years_total[sorted_years[i]]
        
        else:
            run_sum += years_total[sorted_years[i]]
        max_classes = max(max_classes,run_sum)
    return max_classes
print(max_classes(workshops))
        
# question 5

# You are given a number with multiple digits. Construct the 
# largest possible number using exactly those digits.
# Sample:
# Input: 310204
# Output: 432100

def largest_from_digits(n: int) -> int:
    s = str(abs(n))
    digits = sorted(s)

    if n >= 0:
        return int("".join(sorted(s, reverse=True)))

    # n < 0: make smallest number (no leading zeros)
    if digits[0] == '0':
        j = 0
        while j < len(digits) and digits[j] == '0':
            j += 1
        # put first non-zero in front, then zeros, then the rest
        digits[0], digits[j] = digits[j], digits[0]

    return -int("".join(digits))


# question 6

# Given a dictionary where each key maps to a list of words, 
# return the word that appears the most across all lists. 
# If there’s a tie, return any one.

# Sample:

# Input: {"a": ["cat", "dog", "cat"], "b": ["dog", "bird"], "c": ["cat"]}

# Output: "cat"

d = {"a": ["cat", "dog", "cat"], "b": ["dog", "bird"], "c": ["cat"]}

def common_word(d):

    if not d: return None

    freq = dict()
    best_count = 0
    best_word = None

    for val in d.values():
        for v in val:
            freq[v] = freq.get(v,0) + 1
            if freq[v] > best_count:
                best_count = freq[v]
                best_word = v
    return best_word


print(common_word(d))


# question 7
# Determine the maximum number of unique books that can be bought, 
# given an array of book prices and a budget. Each book can be 
# purchased only once.

# Sample:

# Input: prices = [3, 2, 2, 5, 1], budget = 7
prices = [3, 2, 2, 5, 1], budget = 7
# Output: 3

def books(prices,budget):

    prices.sort()
    max_books = 0

    total = 0
    for p in prices:
        total += p
        if total <= budget:
            max_books += 1
        else:
            return max_books
    return max_books

    
# question 8
# Write a function that returns the smallest non-negative number 
# which can be generated by using all the digits with odd values 
# of a given number.

# Sample:

# Input: n = 31020457

# Odd digits are: 3,1,5,7

# Output: 1357
n = 31020457
def odd_num(digit):

    if not digit: return 0

    s = sorted(str(abs(digit)))
    odd = []
    for num in s:
        if int(num) % 2 != 0:
            odd.append(num)
    if not odd: return 0
    return int("".join(odd))
print(odd_num(n))